# Generated by Django 3.2.5 on 2021-07-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeelanding', '0002_cashier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='national_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
